# COLORS
BACKGROUND = "#242424"
WHITE = "#FFF"
GREY = "grey"
BLUE = "#1f6aa5"
DARK_GREY = "#4a4a4a"
CLOSE_RED = "#8a0606"
SLIDER_BG = "#64686b"
DROPDOWN_BG = "#444"
DROPDOWN_HOVER = "#333"
DROPDOWN_MENU = "#666"

# DEFAULT VALUES
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ["None", "X", "Y", "Both"]
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ["None", "Emboss", "Fine Edges", "Contour", "Edge Enhance"]
VIBRANCE_DEFAULT = 1
BRIGHTNESS_DEFAULT = 1
GREYSCALE_DEFAULT = False
INVERT_DEFAULT = False
